baseURL = "https://sacolasmj.netlify.app"
title = "Sacolas MJ"
author = "username"
languageCode = "en"
DefaultContentLanguage = "pt-br"
enableInlineShortcodes = true
theme = "tella"
googleAnalytics = "G-LCYHJL7X90"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Tella Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Sacolas MJ"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Destaque sua marca com sacolas personalizadas de qualidade em plástico, papel e kraft, além de sacos de envio. Escolha entre uma variedade de tamanhos e modelos, e adicione sua logo para uma identidade única."
    meta_og_title = "Sacolas MJ - Sacolas personalizadas de plástico, papel e kraft."
    meta_og_type = "website"
    meta_og_url = "https://sacolasmj.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Destaque sua marca com sacolas personalizadas de qualidade em plástico, papel e kraft, além de sacos de envio. Escolha entre uma variedade de tamanhos e modelos, e adicione sua logo para uma identidade única."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "produtos"
    name = "Produtos"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contato"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1


[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1